INFO 19/Jul/2021 14:10:12 autoreload 10932 140443632052032 Watching for file changes with StatReloader
INFO 19/Jul/2021 14:45:13 autoreload 12858 140011207636800 Watching for file changes with StatReloader
INFO 19/Jul/2021 15:23:37 autoreload 14665 139785805903680 Watching for file changes with StatReloader
INFO 19/Jul/2021 15:24:36 autoreload 14744 140408084182848 Watching for file changes with StatReloader
ERROR 19/Jul/2021 15:25:57 log 14744 140407455635200 Internal Server Error: /api/login
Traceback (most recent call last):
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 172, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'Emp_Codeid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/sql_server/pyodbc/base.py", line 553, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'emp_country_id'. (207) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/monica/Doodle_Project/backend_beautesoftmidyson/cl_table/views.py", line 141, in post
    if serializer.is_valid():
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "/home/monica/Doodle_Project/backend_beautesoftmidyson/cl_table/serializers.py", line 106, in validate
    emp = fmspw[0].Emp_Codeid.pk
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 186, in __get__
    rel_obj = self.get_object(instance)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 153, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/monica/Doodle_Project/env/lib/python3.6/site-packages/sql_server/pyodbc/base.py", line 553, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'emp_country_id'. (207) (SQLExecDirectW)")
ERROR 19/Jul/2021 15:25:57 basehttp 14744 140407455635200 "POST /api/login HTTP/1.1" 500 23345
INFO 19/Jul/2021 15:26:27 autoreload 14744 140408084182848 /home/monica/Doodle_Project/backend_beautesoftmidyson/Cl_beautesoft/settings.py changed, reloading.
INFO 19/Jul/2021 15:26:27 autoreload 14850 140493613041472 Watching for file changes with StatReloader
INFO 19/Jul/2021 15:26:37 autoreload 14850 140493613041472 /home/monica/Doodle_Project/backend_beautesoftmidyson/Cl_beautesoft/settings.py changed, reloading.
